# springboot-devtools
server:
  port: 8080

#debug: true

spring:
  freemarker:
    cache: false # 关闭缓存
    allow-request-override: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    ##################
  thymeleaf:
    cache: false # 关闭缓存


  mvc:
    view:
      prefix: /WEB-INF/JSP/
      suffix: .jsp

  mail:
    host: smtp.163.com
    username: 13103843391@163.com 
    password:  #此处登入用的密码是网易的第三方授权码,不是邮箱密码.在邮箱163邮箱页面上更改授权码.(设置-->客户端授权密码-->重置授权码-->手机短信验证)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  
      
      
      